/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoDePrivacidadRouteImport } from './routes/aviso-de-privacidad'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CasosDeExitoRouteImport } from './routes/casos-de-exito'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as TerminosDeServicioRouteImport } from './routes/terminos-de-servicio'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CasosDeExitoIndexRouteImport } from './routes/casos-de-exito.index'
import { Route as CasosDeExitoSlugRouteImport } from './routes/casos-de-exito.$slug'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadRoute = AvisoDePrivacidadRouteImport.update({
  id: '/aviso-de-privacidad',
  path: '/aviso-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosDeExitoRoute = CasosDeExitoRouteImport.update({
  id: '/casos-de-exito',
  path: '/casos-de-exito',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosDeServicioRoute = TerminosDeServicioRouteImport.update({
  id: '/terminos-de-servicio',
  path: '/terminos-de-servicio',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CasosDeExitoIndexRoute = CasosDeExitoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasosDeExitoRoute,
} as any)
const CasosDeExitoSlugRoute = CasosDeExitoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasosDeExitoRoute,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/blog': typeof BlogRouteWithChildren
  '/casos-de-exito': typeof CasosDeExitoRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/tecnologia': typeof TecnologiaRoute
  '/terminos-de-servicio': typeof TerminosDeServicioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/casos-de-exito/$slug': typeof CasosDeExitoSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/casos-de-exito/': typeof CasosDeExitoIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/clientes': typeof ClientesRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/tecnologia': typeof TecnologiaRoute
  '/terminos-de-servicio': typeof TerminosDeServicioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/casos-de-exito/$slug': typeof CasosDeExitoSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/casos-de-exito': typeof CasosDeExitoIndexRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/blog': typeof BlogRouteWithChildren
  '/casos-de-exito': typeof CasosDeExitoRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/tecnologia': typeof TecnologiaRoute
  '/terminos-de-servicio': typeof TerminosDeServicioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/casos-de-exito/$slug': typeof CasosDeExitoSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/casos-de-exito/': typeof CasosDeExitoIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-de-privacidad'
    | '/blog'
    | '/casos-de-exito'
    | '/clientes'
    | '/contacto'
    | '/nosotros'
    | '/politica-de-cookies'
    | '/servicios'
    | '/tecnologia'
    | '/terminos-de-servicio'
    | '/blog/$slug'
    | '/casos-de-exito/$slug'
    | '/servicios/$slug'
    | '/blog/'
    | '/casos-de-exito/'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidad'
    | '/clientes'
    | '/contacto'
    | '/nosotros'
    | '/politica-de-cookies'
    | '/tecnologia'
    | '/terminos-de-servicio'
    | '/blog/$slug'
    | '/casos-de-exito/$slug'
    | '/servicios/$slug'
    | '/blog'
    | '/casos-de-exito'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/aviso-de-privacidad'
    | '/blog'
    | '/casos-de-exito'
    | '/clientes'
    | '/contacto'
    | '/nosotros'
    | '/politica-de-cookies'
    | '/servicios'
    | '/tecnologia'
    | '/terminos-de-servicio'
    | '/blog/$slug'
    | '/casos-de-exito/$slug'
    | '/servicios/$slug'
    | '/blog/'
    | '/casos-de-exito/'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoDePrivacidadRoute: typeof AvisoDePrivacidadRoute
  BlogRoute: typeof BlogRouteWithChildren
  CasosDeExitoRoute: typeof CasosDeExitoRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  TecnologiaRoute: typeof TecnologiaRoute
  TerminosDeServicioRoute: typeof TerminosDeServicioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidad': {
      id: '/aviso-de-privacidad'
      path: '/aviso-de-privacidad'
      fullPath: '/aviso-de-privacidad'
      preLoaderRoute: typeof AvisoDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos-de-exito': {
      id: '/casos-de-exito'
      path: '/casos-de-exito'
      fullPath: '/casos-de-exito'
      preLoaderRoute: typeof CasosDeExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-de-servicio': {
      id: '/terminos-de-servicio'
      path: '/terminos-de-servicio'
      fullPath: '/terminos-de-servicio'
      preLoaderRoute: typeof TerminosDeServicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/casos-de-exito/': {
      id: '/casos-de-exito/'
      path: '/'
      fullPath: '/casos-de-exito/'
      preLoaderRoute: typeof CasosDeExitoIndexRouteImport
      parentRoute: typeof CasosDeExitoRoute
    }
    '/casos-de-exito/$slug': {
      id: '/casos-de-exito/$slug'
      path: '/$slug'
      fullPath: '/casos-de-exito/$slug'
      preLoaderRoute: typeof CasosDeExitoSlugRouteImport
      parentRoute: typeof CasosDeExitoRoute
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof ServiciosRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CasosDeExitoRouteChildren {
  CasosDeExitoSlugRoute: typeof CasosDeExitoSlugRoute
  CasosDeExitoIndexRoute: typeof CasosDeExitoIndexRoute
}

const CasosDeExitoRouteChildren: CasosDeExitoRouteChildren = {
  CasosDeExitoSlugRoute: CasosDeExitoSlugRoute,
  CasosDeExitoIndexRoute: CasosDeExitoIndexRoute,
}

const CasosDeExitoRouteWithChildren = CasosDeExitoRoute._addFileChildren(
  CasosDeExitoRouteChildren,
)

interface ServiciosRouteChildren {
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosSlugRoute: ServiciosSlugRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoDePrivacidadRoute: AvisoDePrivacidadRoute,
  BlogRoute: BlogRouteWithChildren,
  CasosDeExitoRoute: CasosDeExitoRouteWithChildren,
  ClientesRoute: ClientesRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  TecnologiaRoute: TecnologiaRoute,
  TerminosDeServicioRoute: TerminosDeServicioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
